### ISSUE TITLE
Incorrect underline position when use setSelectedItem

### ISSUE THREAD

**Issue by JustSAT** [bfeher/BFPaperTabBar#2]
Hello,
when i use setSelectedItem method for item between first item index, and last item index, underline position automatically set to item with 0 index.

I inspected the library and found problem in  `-(void)layoutSublayersOfLayer:(CALayer *)layer`. `self.selectedTabIndex` equals to 0.

![img_0838](https://cloud.githubusercontent.com/assets/8726584/12721210/4dbba120-c907-11e5-9cea-ddb9c16c39e8.jpg)

**Comment by bfeher** [comment]
Hi JustSAT.

I'm sorry but I am no longer supporting this library. Please consider using [BFPaperTabBarController](https://github.com/bfeher/BFPaperTabBarController) instead.
